Update

diff --git a/bin/autojs b/bin/autojs
--- a/bin/autojs
+++ b/bin/autojs
@@ -1,24 +1,43 @@
 #!/bin/sh
 
 f_full="$1"
-f_name="${f_full%.*}"
 
 function error() {
-  echo "$@" 1>&2
-  exit 1
+  case $@ in
+    0)
+      echo "Error: invalid assignment." 1>&2
+      exit 1
+      ;;
+    1)
+      echo "Error: invalid filetype." 1>&2
+      exit 1
+      ;;
+    2)
+      echo "Error: autojs.html doesn't exists." 1>&2
+      exit 1
+      ;;
+    *)
+      echo "meow..." 1>&2
+      exit 1
+      ;;
+  esac
+}
+
+function run() {
+  if [ -f "autojs.html" ]; then
+    cp ${f_full} temp.js && open -a "Google Chrome.app" autojs.html
+  elif [ -f "../autojs.html" ]; then
+    cp ${f_full} ../temp.js && open -a "Google Chrome.app" ../autojs.html
+  else
+    error 2
+  fi
 }
 
 if [ -z "$1" ] || [ ! -z "$2" ]; then
-  error "Error: invalid assignment."
+  error 0
+elif [[ "$1" != *.js ]]; then 
+  error 1
+else
+  run
 fi
 
-[[ "$1" != *.js ]] && error "Error: invalid filetype."
-[ ! -f "autojs.html" ] && error "Error: autojs.html doesn't exists."
-
-cp ${f_full} temp.js && \
-  open -a "Google Chrome.app" autojs.html
-
-case "$?" in
-  0 ) exit 0 ;;
-  1 ) exit 1 ;;
-esac
